spring.profiles.active=dev
server.servlet.context-path=/northwind-data
server.port=8080

# JDBC properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://northwind-01-mysql.mysql.database.azure.com:3306/northwind?requireSSL=false&useSSL=true&verifyServerCertificate=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3306/northwind
spring.datasource.username=minad06
spring.datasource.password=Creeper01!
spring.jpa.show-sql=true
##spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.data.rest.base-path=/api
spring.data.rest.default-page-size=20
spring.data.rest.max-page-size=100
spring.data.jpa.repository-packages=org.llin.demo.northwind.repository
spring.data.jpa.entity-packages-to-scan=org.llin.demo.northwind.entity
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=UTC
spring.jpa.open-in-view=false
management.info-env-enabled=true
management.endpoints.web.exposure-include=*
management.endpoints.web.exposure-exclude=health,metrics
info.name=Northwind Data
info.description=Spring Boot Northwind Data Clone
info.version=1.0.0
