\source northwind_authentication.sql
\source northwind_company.sql
\source northwind_customer.sql
\source northwind_inventory_transaction_type.sql     
\source northwind_order_detail_status.sql
\source northwind_order_status.sql    
\source northwind_order_tax_status.sql
\source northwind_payment_type.sql       
\source northwind_privilege.sql       
\source northwind_product.sql                    
\source northwind_purchase_order_status.sql
\source northwind_role.sql      
\source northwind_shipper.sql           
\source northwind_supplier.sql                
\source northwind_type_state.sql
\source northwind_user.sql
