DROP TABLE IF EXISTS COMPANY;

DROP TABLE IF EXISTS COMPANY;
CREATE TABLE COMPANY (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- Combined PK
  NAME VARCHAR(256) DEFAULT NULL
);

DROP TABLE IF EXISTS ORDER_STATUS;

CREATE TABLE ORDER_STATUS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- Combined PK
  STATUS_NAME VARCHAR(256) DEFAULT NULL
);

DROP TABLE IF EXISTS ORDER_TAX_STATUS;

CREATE TABLE ORDER_TAX_STATUS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- Combined PK
  TAX_STATUS_NAME VARCHAR(256) DEFAULT NULL
);




DROP TABLE IF EXISTS PAYMENT_TYPE;

DROP TABLE IF EXISTS PAYMENT_TYPE;
CREATE TABLE PAYMENT_TYPE (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TYPE VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(64) NOT NULL,
  CONSTRAINT TYPE_UNIQUE UNIQUE (TYPE) -- Standard way to do Unique keys
);

DROP TABLE IF EXISTS PRIVILEGE;

CREATE TABLE PRIVILEGE (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRIVILEGE_NAME VARCHAR(50) DEFAULT NULL
);

DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
LAST_NAME VARCHAR(50) DEFAULT NULL,
FIRST_NAME VARCHAR(50) DEFAULT NULL,
EMAIL_ADDRESS VARCHAR(50) DEFAULT NULL,
JOB_TITLE VARCHAR(50) DEFAULT NULL,
BUSINESS_PHONE VARCHAR(25) DEFAULT NULL,
HOME_PHONE VARCHAR(25) DEFAULT NULL,
MOBILE_PHONE VARCHAR(25) DEFAULT NULL,
FAX_NUMBER VARCHAR(25) DEFAULT NULL,
ADDRESS1 VARCHAR(256) DEFAULT NULL,
CITY VARCHAR(50) DEFAULT NULL,
STATE_PROVINCE VARCHAR(50) DEFAULT NULL,
ZIP_POSTAL_CODE VARCHAR(15) DEFAULT NULL,
COUNTRY_REGION VARCHAR(50) DEFAULT NULL,
NOTES LONGTEXT,
COMPANY_ID INT DEFAULT '1',
ADDRESS2 VARCHAR(256) DEFAULT NULL,
WEB_SITE_TITLE VARCHAR(256) DEFAULT NULL,
WEB_SITE_URL VARCHAR(1024) DEFAULT NULL,
PORTRAIT_PATH VARCHAR(1024) DEFAULT NULL,
PORTRAIT_TITLE VARCHAR(256) DEFAULT NULL,
CONSTRAINT FK_CUSTOMER_COMPANY1 FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
); 


DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PRIVILEGE_ID INT DEFAULT '1',
LAST_NAME VARCHAR(50) DEFAULT NULL,
FIRST_NAME VARCHAR(50) DEFAULT NULL,
EMAIL_ADDRESS VARCHAR(50) DEFAULT NULL,
JOB_TITLE VARCHAR(50) DEFAULT NULL,
BUSINESS_PHONE VARCHAR(25) DEFAULT NULL,
HOME_PHONE VARCHAR(25) DEFAULT NULL,
MOBILE_PHONE VARCHAR(25) DEFAULT NULL,
FAX_NUMBER VARCHAR(25) DEFAULT NULL,
ADDRESS1 VARCHAR(256) DEFAULT NULL,
CITY VARCHAR(50) DEFAULT NULL,
STATE_PROVINCE VARCHAR(50) DEFAULT NULL,
ZIP_POSTAL_CODE VARCHAR(15) DEFAULT NULL,
COUNTRY_REGION VARCHAR(50) DEFAULT NULL,
NOTES LONGTEXT,
COMPANY_ID INT DEFAULT '1',
WEB_SITE_URL VARCHAR(1024) DEFAULT NULL,
WEB_SITE_TITLE VARCHAR(256) DEFAULT NULL,
PORTRAIT_PATH VARCHAR(1024) DEFAULT NULL,
PORTRAIT_TITLE VARCHAR(256) DEFAULT NULL,
ADDRESS2 VARCHAR(256) DEFAULT NULL,
CONSTRAINT FK_EMPLOYEE_COMPANY1 FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT FK_EMPLOYEE_PRIVILEGE1 FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);


DROP TABLE IF EXISTS SHIPPER;

CREATE TABLE SHIPPER (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
COMPANY_ID INT NOT NULL,
LAST_NAME VARCHAR(50) DEFAULT NULL,
FIRST_NAME VARCHAR(50) DEFAULT NULL,
EMAIL_ADDRESS VARCHAR(50) DEFAULT NULL,
JOB_TITLE VARCHAR(50) DEFAULT NULL,
BUSINESS_PHONE VARCHAR(25) DEFAULT NULL,
HOME_PHONE VARCHAR(25) DEFAULT NULL,
MOBILE_PHONE VARCHAR(25) DEFAULT NULL,
FAX_NUMBER VARCHAR(25) DEFAULT NULL,
ADDRESS1 VARCHAR(256) DEFAULT NULL,
CITY VARCHAR(50) DEFAULT NULL,
STATE_PROVINCE VARCHAR(50) DEFAULT NULL,
ZIP_POSTAL_CODE VARCHAR(15) DEFAULT NULL,
COUNTRY_REGION VARCHAR(50) DEFAULT NULL,
NOTES LONGTEXT,
ADDRESS2 VARCHAR(256) DEFAULT NULL,
WEB_SITE_URL VARCHAR(1024) DEFAULT NULL,
WEB_SITE_TITLE VARCHAR(256) DEFAULT NULL,
PORTRAIT_PATH VARCHAR(1024) DEFAULT NULL,
PORTRAIT_TITLE VARCHAR(256) DEFAULT NULL,
CONSTRAINT FK_SHIPPER_COMPANY1 FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS CUSTOMER_ORDER;

CREATE TABLE CUSTOMER_ORDER (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
EMPLOYEE_ID INT DEFAULT NULL,
CUSTOMER_ID INT NOT NULL,
ORDER_DATE DATETIME NOT NULL,
SHIPPED_DATE DATETIME DEFAULT NULL,
SHIPPER_ID INT DEFAULT NULL,
SHIP_NAME VARCHAR(50) DEFAULT NULL,
SHIP_ADDRESS LONGTEXT,
SHIP_CITY VARCHAR(50) DEFAULT NULL,
SHIP_STATE_PROVINCE VARCHAR(50) DEFAULT NULL,
SHIP_ZIP_POSTAL_CODE VARCHAR(50) DEFAULT NULL,
SHIP_COUNTRY_REGION VARCHAR(50) DEFAULT NULL,
SHIPPING_FEE DECIMAL(19,4) DEFAULT '0.0000',
TAXES DECIMAL(19,4) DEFAULT '0.0000',
PAYMENT_TYPE_ID INT DEFAULT NULL,
PAID_DATE DATETIME DEFAULT NULL,
NOTES LONGTEXT,
TAX_RATE DOUBLE DEFAULT '0',
TAX_STATUS_ID INT DEFAULT NULL,
STATUS_ID INT DEFAULT '0',
PAYMENT_TYPE VARCHAR(255) DEFAULT NULL,
CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT FK_ORDER_EMPLOYEE1 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT FK_ORDER_ORDER_STATUS1 FOREIGN KEY (STATUS_ID) REFERENCES ORDER_STATUS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT FK_ORDER_ORDER_TAX_STATUS1 FOREIGN KEY (TAX_STATUS_ID) REFERENCES ORDER_TAX_STATUS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT FK_ORDER_PAYMENT_TYPE1 FOREIGN KEY (PAYMENT_TYPE_ID) REFERENCES PAYMENT_TYPE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT FK_ORDER_SHIPPER1 FOREIGN KEY (SHIPPER_ID) REFERENCES SHIPPER (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

